### ISSUE TITLE
 [전체 단어 목록] 정렬 저장 안됨

### ISSUE THREAD

**Issue by dev-Rhea** [Murakano/murakano-fe#84]
**버그 설명**
기본 정렬 순서가 아닌, 인기순으로 선택후 스크롤 복구시 정렬 초기화

**재현하는 방법**
동작을 재현하는 단계:
1. 인기순으로 정렬
2. 목록의 단어 클릭 
3. 검색결과 페이지로 이동 후, 뒤로 가기를 통해 전체 단어목록으로 복귀
4. 인기순이 아닌 최신순 으로 정렬 초기화 된 상태에서 스크롤 위치 복구

**예상한 동작**
기존 정렬 순서에 맞춰 스크롤 복구 

**스크린샷**
https://github.com/user-attachments/assets/bd6a870f-54de-49d1-b832-e28c21743377

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [Mac OS]
 - Browser [chrome]
 - Version [126.0.6478.127]

**추가적인 내용:**
정렬 저장 필요

**Comment by jjikky** [comment]
https://github.com/Murakano/murakano-fe/commit/21aa0bedc0e9f0fef66c95cb2bdef08c9fd8da16
해결 ! ( 커밋에 이슈 번호 잘 못 적었습니다..ㅜㅜ )
